/*
Modify your code from the previous exercise so that it could easily
be modified to display a different range of numbers (instead of 1234567890)
and a different number of repetitions of those numbers (instead of 60
total characters), with the vertical bars still matching up correctly.
 Use class constants instead of “magic numbers.”
 Here are some example outputs that could be generated by changing
 your constants:

    |    |    |    |    |    |    |    |    |    |
12340123401234012340123401234012340123401234012340
       |       |       |       |       |       |       |
12345670123456701234567012345670123456701234567012345670
*/
public class Chapter02Exercise11 {

  public static final int SCALE = 7;
  public static final int COUNT = 7;

  public static void main(String[] args) {

    pipes();
    numbers();

  }

  // method for columns
  public static void pipes() {
    for (int i = 1; i <= SCALE; i++) {
      for (int j = 1; j <= COUNT; j++) {
        System.out.print(" ");
      }
      System.out.print("|");
    }
    System.out.println();
  }

  // method for numbers
  public static void numbers() {
    String nums = "";
    for (int i = 1; i <= SCALE; i ++) {
      for (int j = 1; j <= COUNT; j++) {
          nums += j;
      }
      nums += "0";
    }
    System.out.println(nums);
  }
}
